---

- name: assert | Test if bareos_repository_type is set correctly
  ansible.builtin.assert:
    that:
      - bareos_repository_type is defined
      - bareos_repository_type in [ "community", "subscription" ]
    quiet: yes

- name: assert | Test if bareos_repository_username is set correctly
  ansible.builtin.assert:
    that:
      - bareos_repository_username is defined
      - bareos_repository_username is string
      - bareos_repository_username != ""
    quiet: yes
  when:
    - bareos_repository_type == "subscription"

- name: assert | Test if bareos_repository_password is set correctly
  ansible.builtin.assert:
    that:
      - bareos_repository_password is defined
      - bareos_repository_password is string
      - bareos_repository_password != ""
    quiet: yes
  when:
    - bareos_repository_type == "subscription"

- name: assert | Test if bareos_repository_release is set correctly
  ansible.builtin.assert:
    that:
      - bareos_repository_release is defined
      - bareos_repository_release in [ "current", "next", "release" ]
    quiet: yes
