---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  vars:
    _bareos_repository_verify_packages:
      default:
        - bareos
      Debian:
        - bareos-common
    bareos_repository_verify_packages: "{{ _bareos_repository_verify_packages[ansible_os_family] | default(_bareos_repository_verify_packages['default']) }}"

  tasks:
    - name: Test if bareos packages can be installed
      ansible.builtin.package:
        name: "{{ bareos_repository_verify_packages }}"
      notify:
        - Remove packages

  handlers:
    - name: Remove packages
      ansible.builtin.package:
        name: "{{ bareos_repository_verify_packages }}"
        state: absent
