---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Test if the repository can be used
      ansible.builtin.package:
        name: bareos
      notify:
        - Remove bareos
  
  handlers:
    - name: Remove bareos
      ansible.builtin.package:
        name: bareos
        state: absent
